# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

version: 2
updates:
- package-ecosystem: maven
  directory: /
  schedule:
    interval: monthly
  ignore:
    # Ignore some updates to the 'io.github.mavenplugins:unleash-utils' artifact
    - dependency-name: "io.github.mavenplugins:unleash-utils"
      versions: ["3.0.2"]
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
